@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gabriel Naves",
  "email": "gabriel.naves@example.com",
  "password": "password123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###

# @name questions
POST  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "My Question Title 3",
  "content": "This is the content of my question."
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=3
Content-Type: application/json
Authorization: Bearer {{authToken}}
